// Auto generated by compass meta-data ant task at: Sun Feb 05 23:58:23 GMT 2006
package org.compass.sample.petclinic;

/**
 * Petclinic Meta Data
 */
public final class Petclinic {
	/**
	 * Petclinic Meta Data
	 */
	public static final class Group {
		public static final String Id = "petclinic";
		public static final String DispayName = "Petclinic Meta Data";
		public static final String Uri = "http://compass/sample/petclinic";
	}

	public static final class Alias {
		/**
		 * Owner alias
		 */
		public static final class Owner {
			public static final String Id = "owner";
			public static final String Name = "owner";
			public static final String DisplayName = "Owner";
			public static final String Uri = "http://compass/sample/petclinic/alias/owner";
			public static final String GroupId = "petclinic";
		}

		/**
		 * Vet alias
		 */
		public static final class Vet {
			public static final String Id = "vet";
			public static final String Name = "vet";
			public static final String DisplayName = "Vet";
			public static final String Uri = "http://compass/sample/petclinic/alias/vet";
			public static final String GroupId = "petclinic";
		}

		/**
		 * Pet Type alias
		 */
		public static final class PetType {
			public static final String Id = "petType";
			public static final String Name = "petType";
			public static final String DisplayName = "Pet Type";
			public static final String Uri = "http://compass/sample/petclinic/alias/petType";
			public static final String GroupId = "petclinic";
		}

		/**
		 * Specialty alias
		 */
		public static final class Specialty {
			public static final String Id = "specialty";
			public static final String Name = "specialty";
			public static final String DisplayName = "Specialty";
			public static final String Uri = "http://compass/sample/petclinic/alias/specialty";
			public static final String GroupId = "petclinic";
		}

		/**
		 * Pet alias
		 */
		public static final class Pet {
			public static final String Id = "pet";
			public static final String Name = "pet";
			public static final String DisplayName = "Pet";
			public static final String Uri = "http://compass/sample/petclinic/alias/pet";
			public static final String GroupId = "petclinic";
		}

		/**
		 * Visit alias
		 */
		public static final class Visit {
			public static final String Id = "visit";
			public static final String Name = "visit";
			public static final String DisplayName = "Visit";
			public static final String Uri = "http://compass/sample/petclinic/alias/visit";
			public static final String GroupId = "petclinic";
		}

	}

	public static final class MetaData {
		/**
		 * Type of an entity in the system
		 */
		public static final class Type {
			public static final String Id = "type";
			public static final String Name = "type";
			public static final String DisplayName = "Type";
			public static final String Uri = "http://compass/sample/petclinic/type";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The specialty of a vet
		 */
		public static final class Specialty {
			public static final String Id = "specialty";
			public static final String Name = "specialty";
			public static final String DisplayName = "Specialty";
			public static final String Uri = "http://compass/sample/petclinic/specialty";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The type of a pet
		 */
		public static final class PetType {
			public static final String Id = "petType";
			public static final String Name = "petType";
			public static final String DisplayName = "Pet Type";
			public static final String Uri = "http://compass/sample/petclinic/petType";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The description of a visit
		 */
		public static final class Description {
			public static final String Id = "description";
			public static final String Name = "description";
			public static final String DisplayName = "Description";
			public static final String Uri = "http://compass/sample/petclinic/description";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The telephone of a person
		 */
		public static final class Telephone {
			public static final String Id = "telephone";
			public static final String Name = "telephone";
			public static final String DisplayName = "Telephone";
			public static final String Uri = "http://compass/sample/petclinic/telephone";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The address of a person
		 */
		public static final class Address {
			public static final String Id = "address";
			public static final String Name = "address";
			public static final String DisplayName = "Address";
			public static final String Uri = "http://compass/sample/petclinic/address";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The date
		 */
		public static final class Date {
			public static final String Id = "date";
			public static final String Name = "date";
			public static final String DisplayName = "Date";
			public static final String Uri = "http://compass/sample/petclinic/date";
			public static final String GroupId = "petclinic";
			public static final String Format = "yyyy-MM-dd";
		}

		/**
		 * The name of an entity
		 */
		public static final class Name {
			public static final String Id = "name";
			public static final String Name = "name";
			public static final String DisplayName = "Name";
			public static final String Uri = "http://compass/sample/petclinic/name";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The birthdate
		 */
		public static final class Birthdate {
			public static final String Id = "birthdate";
			public static final String Name = "birthdate";
			public static final String DisplayName = "Birthdate";
			public static final String Uri = "http://compass/sample/petclinic/birthdate";
			public static final String GroupId = "petclinic";
			public static final String Format = "yyyy-MM-dd";
		}

		/**
		 * The city of a person
		 */
		public static final class City {
			public static final String Id = "city";
			public static final String Name = "city";
			public static final String DisplayName = "City";
			public static final String Uri = "http://compass/sample/petclinic/city";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The first name of a person
		 */
		public static final class FirstName {
			public static final String Id = "firstName";
			public static final String Name = "firstName";
			public static final String DisplayName = "First Name";
			public static final String Uri = "http://compass/sample/petclinic/firstName";
			public static final String GroupId = "petclinic";
		}

		/**
		 * The last name of a person
		 */
		public static final class LastName {
			public static final String Id = "lastName";
			public static final String Name = "lastName";
			public static final String DisplayName = "Last Name";
			public static final String Uri = "http://compass/sample/petclinic/lastName";
			public static final String GroupId = "petclinic";
		}

	}

}

